-----------------BDS DTH RANGE X COMPL----------
DROP TABLE XXX_BD_RGQ_DTH
SELECT *
INTO XXX
FROM XXX
WHERE DT_ABERT >='2013-07-01'
	AND DT_ABERT <'2013-10-01'
	AND TERMINAL IS NOT NULL
ORDER BY DT_ABERT

---(26715 linha(s) afetadas)---

UPDATE XXX
SET DT_BAIXA = '2013-10-01 00:00:00.000' 
WHERE DT_BAIXA IS NULL

---(0 linha(s) afetadas)---

DROP TABLE XXX
SELECT	CN_ID_ASSINATURA,
		CPF,
		TELEFONE,
		TERMINAL,
		DDD,
		DT_ABERT,
		DT_BAIXA,
		DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) AS DURACAO,
		CASE WHEN DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) BETWEEN 0 AND 8 THEN '0-8H'
		WHEN DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) BETWEEN 9 AND 16 THEN '8-16H'
		WHEN DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) BETWEEN 17 AND 24 THEN '16-24H'
		WHEN DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) BETWEEN 25 AND 48 THEN '24-48H'
		WHEN DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) BETWEEN  49 AND 60 THEN '48-60H'
		WHEN DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) BETWEEN 61 AND 72 THEN '60-72H'
		WHEN DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) BETWEEN 73 AND 84 THEN '72-84H'
		WHEN DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) BETWEEN 85 AND 96 THEN '84-96H'
		WHEN DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) BETWEEN 97 AND	108 THEN '96-108H'
		WHEN DATEDIFF (HOUR, DT_ABERT, DT_BAIXA) BETWEEN 109 AND 120 THEN '108-120H'
		ELSE '>120H' END RANGE,
		MES
INTO XXX
FROM XXX
WHERE (TERMINAL <>'0' OR CPF <>'0')



----CRUZAMENTO BDS X COMPL REPARO------------

DROP TABLE XXX
SELECT A.*
	,CASE WHEN EXISTS (SELECT 1 FROM XXX  B
	WHERE B.MOTIVO = 'REPARO' AND (B.DT_COMPL BETWEEN A.DT_ABERT AND A.DT_BAIXA) AND (A.TERMINAL = B.DDD_TERMINAL)) THEN '1' ELSE '0' END COMPL
INTO XXX
FROM XXX
WHERE TERMINAL <>'0'

INSERT INTO XXX
SELECT A.*
	,CASE WHEN EXISTS (SELECT 1 FROM XXX  B
	WHERE B.MOTIVO = 'REPARO' AND (B.DT_COMPL BETWEEN A.DT_ABERT AND A.DT_BAIXA) AND (A.cpf = B.cpf)) THEN '1' ELSE '0' END COMPL
FROM XXX
WHERE TERMINAL = '0'


------COUNT EXCEL------
SELECT COUNT (1) VOLUME,
		MES,
		RANGE,
		COMPL
FROM XXX
WHERE MES IN ('7','8','9')
GROUP BY 	
	MES,
	RANGE,
	COMPL

-----------------BDS REINCIDÊNCIA X COMPL----------
DROP TABLE XXX
SELECT A.*
	,CASE WHEN EXISTS (SELECT 1 FROM XXX  B
	WHERE B.MOTIVO = 'REPARO' AND ((B.DT_COMPL BETWEEN A.DT_ABERT AND A.DT_BAIXA) OR (DATEDIFF (DAY, A.DT_BAIXA, B.DT_COMPL) BETWEEN 0 AND 7)) AND (A.TERMINAL = B.DDD_TERMINAL)) THEN '1' ELSE '0' END COMPL
INTO XXX
FROM XXX
WHERE TERMINAL <>'0'

INSERT INTO XXX
SELECT A.*
	,CASE WHEN EXISTS (SELECT 1 FROM XXX  B
	WHERE B.MOTIVO = 'REPARO' AND ((B.DT_COMPL BETWEEN A.DT_ABERT AND A.DT_BAIXA) OR (DATEDIFF (DAY, A.DT_BAIXA, B.DT_COMPL) BETWEEN 0 AND 7)) AND ( A.CPF = B.CPF)) THEN '1' ELSE '0' END COMPL
FROM XXX
WHERE TERMINAL = '0'

-----REINCIDENCIA EXCEL---------
SELECT * FROM XXX
WHERE MES IN ('7','8','9')
ORDER BY TERMINAL, CPF, DT_ABERT


