/**********RECORTE RECLAMAÇÕES E MARCA CONTRATO***********/

DROP TABLE XXX

SELECT *
INTO XXX
FROM 
	(SELECT 
		A.DATAREGISTROSOLICITACAO
		,A.CODSOLICITACAO
		,A.OBSERVACAO
		,C.NUM_TEL AS TERMINAL
		,C.NM_GRUPO_SUBTP_PC
		,B.CONTRATADA
		,CASE WHEN C.NUM_TEL IS NOT NULL THEN 'RTB' ELSE 'NÃO LOCALIZADO' END PRODUTO_PLANTA
		,CPFUSUARIO
		,CNPJUSUARIO
		,DATEPART(WEEK,DATAREGISTROSOLICITACAO) SEMANA
		,ROW_NUMBER () OVER (PARTITION BY CODSOLICITACAO ORDER BY C.NUM_TEL ASC)AS REP
	FROM XXX A
	LEFT JOIN XXX B
		ON A.AREA_XXX = B.AT
		AND A.ESCRITORIO_SERVICO = B.ES
		AND A.CNL = B.CNL
	LEFT JOIN XXX C
		ON (A.CPFUSUARIO = C.NR_DCMO_PRNL OR A.terminalXXX = C.NUM_TEL)
	WHERE A.DATAREGISTROSOLICITACAO >='2014-07-01' -----------------INICIO MÊS ANALISE
		AND A.DATAREGISTROSOLICITACAO <'2014-08-01'-----------------FIM MÊS ANALISE
		AND A.MOTIVO = 'REPARO'
		AND SERVICO ='%FIXO%') D WHERE REP = '1'

---ARVORE NÃO LOCALIZADO PLANTA RTB

SELECT 
	COUNT (1)
	,PRODUTO_PLANTA
 FROM XXX 
 WHERE NM_GRUPO_SUBTP_PC = 'RES' OR NM_GRUPO_SUBTP_PC IS NULL
 GROUP BY PRODUTO_PLANTA
	

/****************MARCAÇÃO BDS - PRAZO, GRUPO E REINCIDENCIA******************/

DROP TABLE XXX

SELECT 
	A.TERMINAL
	,B.CONTRATADA
	,A.DT_RECLAMACAO
	,A.DT_ENCERRAMENTO
	,A.ID_PRODUTO
	,B.CODSOLICITACAO
	,B.SEMANA
	,A.GESTOR
	,CASE WHEN DT_ENCERRAMENTO IS NOT NULL AND DATEDIFF (HOUR, DT_RECLAMACAO, DT_ENCERRAMENTO) <=24 THEN 'S'
	 WHEN DT_ENCERRAMENTO IS NOT NULL AND DATEDIFF (HOUR, DT_RECLAMACAO, DT_ENCERRAMENTO) >24 THEN 'N' ELSE NULL END CUMPR_PRAZO 
	,CASE WHEN A.TERMINAL = B.TERMINAL AND DT_ENCERRAMENTO IS NOT NULL THEN DATEDIFF (HOUR, DT_RECLAMACAO, DT_ENCERRAMENTO) 
	WHEN A.TERMINAL = B.TERMINAL AND DT_ENCERRAMENTO IS NULL THEN DATEDIFF (HOUR, DT_RECLAMACAO, GETDATE()) ELSE NULL END PRAZO 
	,CASE WHEN 	(A.DT_ENCERRAMENTO IS NOT NULL AND A.DT_ENCERRAMENTO <= B.DATAREGISTROSOLICITACAO AND DATEDIFF(DAY,A.DT_ENCERRAMENTO, B.DATAREGISTROSOLICITACAO) <='7' AND DATEDIFF(DAY,A.DT_ENCERRAMENTO, B.DATAREGISTROSOLICITACAO) >='0') THEN 'ENCERRADO DE 0 A 7D ANTES DA RECLAMAÇÃO'
	WHEN(A.DT_ENCERRAMENTO IS NOT NULL AND A.DT_ENCERRAMENTO > B.DATAREGISTROSOLICITACAO AND DATEDIFF(DAY,A.DT_RECLAMACAO, B.DATAREGISTROSOLICITACAO) <='20' AND DATEDIFF(DAY,A.DT_RECLAMACAO, B.DATAREGISTROSOLICITACAO) >='0') THEN 'ENCERRADO APÓS RECLAMAÇÃO E EMITIDO ATÉ 20DIAS ANTES'
	WHEN(A.DT_ENCERRAMENTO IS NULL AND DATEDIFF(DAY,A.DT_RECLAMACAO, B.DATAREGISTROSOLICITACAO) <='20' AND DATEDIFF(DAY,A.DT_RECLAMACAO, B.DATAREGISTROSOLICITACAO) >='0')THEN 'EM ABERTO EMITIDO ATÉ 20DIAS ANTES DA RECLAMAÇÃO' ELSE NULL END GRUPO_BD
	,ROW_NUMBER () OVER (PARTITION BY CODSOLICITACAO ORDER BY DT_RECLAMACAO ASC) AS REINC
	,ROW_NUMBER () OVER (PARTITION BY CODSOLICITACAO ORDER BY DT_RECLAMACAO DESC) AS REP
INTO XXX
FROM (SELECT * FROM XXX
		WHERE NM_GRUPO_SUBTP_PC = 'RES')  B
LEFT JOIN (SELECT * FROM XXX
			WHERE DT_RECLAMACAO >='2014-06-01')A
	ON A.TERMINAL = B.TERMINAL AND 
	((A.DT_ENCERRAMENTO IS NOT NULL AND A.DT_ENCERRAMENTO <= B.DATAREGISTROSOLICITACAO AND DATEDIFF(DAY,A.DT_ENCERRAMENTO, B.DATAREGISTROSOLICITACAO) <='7' AND DATEDIFF(DAY,A.DT_ENCERRAMENTO, B.DATAREGISTROSOLICITACAO) >='0')
	OR(A.DT_ENCERRAMENTO IS NOT NULL AND A.DT_ENCERRAMENTO > B.DATAREGISTROSOLICITACAO AND DATEDIFF(DAY,A.DT_RECLAMACAO, B.DATAREGISTROSOLICITACAO) <='20' AND DATEDIFF(DAY,A.DT_RECLAMACAO, B.DATAREGISTROSOLICITACAO) >='0')
	OR(A.DT_ENCERRAMENTO IS NULL AND DATEDIFF(DAY,A.DT_RECLAMACAO, B.DATAREGISTROSOLICITACAO) <='20' AND DATEDIFF(DAY,A.DT_RECLAMACAO, B.DATAREGISTROSOLICITACAO) >='0'))


---ARVORE BD----
SELECT
	SUM(CASE WHEN DT_RECLAMACAO IS NOT NULL AND REP = '1' THEN 1 END) COM_BD
	,SUM(CASE WHEN DT_RECLAMACAO IS NULL AND REP = '1' THEN 1 END) SEM_BD
	,SUM(CASE WHEN DT_RECLAMACAO IS NOT NULL AND REP = '1' AND REINC <>'1' THEN 1 END) REINCIDENCIA_BD
	,SUM(CASE WHEN DT_RECLAMACAO IS NOT NULL AND REP = '1' AND REINC ='1' AND CUMPR_PRAZO ='S' AND GRUPO_BD = 'ENCERRADO APÓS RECLAMAÇÃO E EMITIDO ATÉ 20DIAS ANTES' THEN 1 END)BD_NO_PRAZO_EM_ABERTO_RECLAMAÇÃO
	,SUM(CASE WHEN DT_RECLAMACAO IS NOT NULL AND REP = '1' AND REINC ='1' AND CUMPR_PRAZO ='S' AND GRUPO_BD = 'ENCERRADO DE 0 A 7D ANTES DA RECLAMAÇÃO' THEN 1 END)BD_NO_PRAZO_ENCERR_ANTES_RECLAMAÇÃO
	,SUM(CASE WHEN DT_RECLAMACAO IS NOT NULL AND REP = '1' AND REINC ='1' AND CUMPR_PRAZO ='N' THEN 1 END) BD_FORA_PRAZO
	,SUM(CASE WHEN DT_RECLAMACAO IS NOT NULL AND REP = '1' AND REINC ='1' AND CUMPR_PRAZO IS NULL THEN 1 END) BD_EM_ABERTO
FROM XXX 


---QUEBRA QUANTIDADE REINCIDÊNCIA--
SELECT
	COUNT(1) VOLUME
	,REINC
FROM XXX
WHERE DT_RECLAMACAO IS NOT NULL AND REP = '1' AND REINC <>'1' 
GROUP BY REINC

---QUEBRA SLA CLIENTES BD FORA PRAZO--

SELECT
	COUNT(1)
	,PRAZO
FROM XXX
WHERE DT_RECLAMACAO IS NOT NULL AND REP = '1' AND REINC ='1' AND CUMPR_PRAZO ='N' 
GROUP BY PRAZO

---QUEBRA SLA CLIENTES BD EM ABERTO--

SELECT
	COUNT(1)
	,PRAZO/24----PRAZO EM DIAS
FROM XXX
WHERE DT_RECLAMACAO IS NOT NULL AND REP = '1' AND REINC ='1' AND CUMPR_PRAZO IS NULL 
GROUP BY PRAZO/24

---QUEBRA SLA CLIENTES BD NO PRAZO-----

SELECT
	COUNT(1)
	,GRUPO_BD
	,PRAZO
FROM XXX
WHERE DT_RECLAMACAO IS NOT NULL AND REP = '1' AND REINC ='1' AND CUMPR_PRAZO ='S' 
GROUP BY PRAZO	
		,GRUPO_BD


/*****************SEM BD E MARCAÇÃO CHAMADAS CAT ATÉ 7D ANTES DA RECLAMAÇÃO CLIENTES SEM BD*************/

DROP TABLE XXX	

SELECT 
	*
INTO XXX
FROM 
(SELECT 
	A.*
	,B.DT_ABERTURA
	,CASE WHEN  DS_CAUSA LIKE '%MASSIVA%' THEN 'MASSIVA' 
	WHEN DS_CAUSA NOT LIKE '%MASSIVA%'AND DS_FECHAMENTO LIKE '%BD%' THEN 'BD EMITIDO'
	ELSE NULL END VERBALIZAÇÃO
	,ROW_NUMBER () OVER (PARTITION BY CODSOLICITACAO ORDER BY DT_ABERTURA ASC) AS REINC
	,ROW_NUMBER () OVER (PARTITION BY CODSOLICITACAO ORDER BY DT_ABERTURA DESC) AS REP
FROM (SELECT * FROM XXX
	  WHERE DT_RECLAMACAO IS NULL) A
LEFT JOIN (SELECT * FROM XXX 
			WHERE DT_ABERTURA >='2014-06-01')B
	ON A.TERMINAL = left(B.CD_TERMINAL,10)
	AND A.DATAREGISTROSOLICITACAO >= B.DT_ABERTURA 
	AND DATEDIFF(DAY, DT_ABERTURA, DATAREGISTROSOLICITACAO) <='7')C WHERE REP ='1'
	
----ARVORE SEM BD  E COM CRUZAMENTO CAT	

SELECT
	SUM(CASE WHEN DT_ABERTURA IS NULL THEN 1 END)SEM_CHAMADA_CAT
	,SUM(CASE WHEN DT_ABERTURA IS NOT NULL THEN 1 END)COM_CHAMADA_CAT
	,SUM(CASE WHEN DT_ABERTURA IS NOT NULL AND VERBALIZACAO = 'MASSIVA' THEN 1 END)COM_CHAMADA_CAT_MASSIVA
	,SUM(CASE WHEN DT_ABERTURA IS NOT NULL AND VERBALIZACAO = 'BD EMITIDO' THEN 1 END) COM_CHAMADA_CAT_BD_EMITIDO
	,SUM(CASE WHEN DT_ABERTURA IS NOT NULL AND VERBALIZACAO NOT IN ('MASSIVA','BD EMITIDO') THEN 1 END) COM_CHAMADA_CAT_OUTROS
FROM XXX
		
	
/******************SEM BD E CAT E MARCAÇÃO CHAMADAS PLATAFORMA ATÉ 7D ANTES DA RECLAMAÇÃO**************/

DROP TABLE XXX

SELECT 
	* 
INTO XXX	
FROM 
(SELECT 
	A.*
	,B.D_DATA
	,B.N_DIALOGO
	,B.VDN
	,CASE WHEN (FLUXO LIKE '%-34-%')THEN 'MASSIVA' ELSE 'DEMAIS' END VERBALIZACAO_PLAT
	,ROW_NUMBER () OVER (PARTITION BY CODSOLICITACAO ORDER BY D_DATA ASC) AS REINC
	,ROW_NUMBER () OVER (PARTITION BY CODSOLICITACAO ORDER BY D_DATA DESC) AS REP
FROM (SELECT * FROM XXX
	  WHERE DT_ABERTURA IS NULL) A
LEFT JOIN (SELECT ID_PLATAFORMA, N_DIALOGO, D_DATA, TERMINAL_INFORMADO, VDN FROM XXX
			WHERE S_ASSUNTO = 'REPAROS' AND S_ASSUNTOSEC LIKE '%LINHA%' AND D_DATA >='2014-06-01')B
	ON A.TERMINAL = B.TERMINAL_INFORMADO
	AND A.DATAREGISTROSOLICITACAO >= B.D_DATA 
	AND DATEDIFF(DAY, D_DATA, DATAREGISTROSOLICITACAO) <='7') C WHERE REP ='1'
	
----ARVORE SEM BD, SEM CAT E COM CRUZAMENTO PLATAFORMA	

SELECT
	SUM(CASE WHEN D_DATA IS NULL THEN 1 END)SEM_CHAMADA_PLATAFORMA
	,SUM(CASE WHEN D_DATA IS NOT NULL THEN 1 END)COM_CHAMADA_PLATAFORMA
	,SUM(CASE WHEN D_DATA IS NOT NULL AND N_DIALOGO ='1' THEN 1 END)COM_CHAMADA_PLATAFORMA_RETIDA
	,SUM(CASE WHEN D_DATA IS NOT NULL AND N_DIALOGO ='1' AND VERBALIZACAO_PLAT = 'MASSIVA' THEN 1 END) COM_CHAMADA_PLATAFORMA_RETIDA_MASSIVA
	,SUM(CASE WHEN D_DATA IS NOT NULL AND N_DIALOGO ='1' AND VERBALIZACAO_PLAT <> 'MASSIVA' THEN 1 END) COM_CHAMADA_PLATAFORMA_RETIDA_OUTROS
	,SUM(CASE WHEN D_DATA IS NOT NULL  AND N_DIALOGO ='2'  THEN 1 END) COM_CHAMADA_PLATAFORMA_NÃO_RETIDA
FROM XXX			

---VDNS CHAMADAS TRANSFERIDAS PLATAFORMA----

SELECT 
	COUNT(1)
	,VDN
FROM XXX
WHERE D_DATA IS NOT NULL  AND N_DIALOGO ='2' 
GROUP BY VDN
