-----------RECORTE PLATAFORMA----------

DROP TABLE XXX
SELECT 
	ID_PLATAFORMA
	,D_DATA
	,TERMINAL_INFORMADO	
	,S_ASSUNTOSEC
	,S_MCDU
	,N_DIALOGO
	,S_ASSUNTO
	,CASE WHEN S_ASSUNTO = 'CONTAS' THEN '1' ELSE '0' END CONTAS
	,CASE WHEN S_ASSUNTO = 'REPAROS' THEN '1' ELSE '0' END REPARO
	,CASE WHEN S_ASSUNTO = 'AQUISIÇÃO' THEN '1' ELSE '0' END AQUISIÇÃO
	,CASE WHEN S_ASSUNTO = 'COMERCIAL' THEN '1' ELSE '0' END COMERCIAL
INTO XXX
FROM XXX
WHERE S_MCDU  IN ('XXX') 
AND N_DIALOGO = '2'
AND D_DATA >='2013-12-01' AND D_DATA < '2014-01-01'
AND S_ASSUNTOSEC ='TV'


------------AGING-------
DROP TABLE XXX
SELECT 
	A.*
	,DT_INST
	,CASE WHEN DATEDIFF (DAY, B.DT_INST, A.D_DATA) BETWEEN 0 AND 10 THEN 'ATE 10D'
	 WHEN DATEDIFF (DAY,B.DT_INST, A.D_DATA) BETWEEN 11 AND 45 THEN '11 A 45D'
	 WHEN DATEDIFF (DAY, B.DT_INST, A.D_DATA) BETWEEN 46 AND 90 THEN '46 A 90D'
	 WHEN DATEDIFF (DAY, B.DT_INST, A.D_DATA) >90 THEN '>90D' ELSE 'NÃO LOCALIZADO' END AGING
	,ROW_NUMBER () OVER (PARTITION BY ID_PLATAFORMA ORDER BY D_DATA) AS REP
INTO XXX
FROM XXX A
LEFT JOIN XXX B
ON CONVERT(VARCHAR,A.TERMINAL_INFORMADO) = CONVERT(VARCHAR,B.NM_DDD_RES)+CONVERT(VARCHAR,B.NM_TEL_RES) 



-----REINCIDENCIA--------
DROP TABLE XXX
SELECT *
INTO XXX
FROM XXX
WHERE REP = '1'

DROP TABLE XXX
SELECT *
	,ROW_NUMBER () OVER (PARTITION BY TERMINAL_INFORMADO ORDER BY D_DATA ASC) AS REINC
INTO XXX
FROM XXX


DROP TABLE XXX
SELECT *
	,ROW_NUMBER () OVER (PARTITION BY TERMINAL_INFORMADO ORDER BY REINC DESC) AS REINC_MAX
INTO XXX
FROM XXX


	
SELECT
	COUNT (1) AS VOLUME
	,AGING
	,S_ASSUNTO
	,REINC
FROM XXX
WHERE REINC_MAX = '1' AND REP ='1'
GROUP BY
	AGING
	,S_ASSUNTO
	,REINC
	
SELECT
	COUNT (1) AS VOLUME
	,AGING
	,S_ASSUNTO
	,REINC
FROM XXX
where REP = '1' 
GROUP BY
	AGING
	,S_ASSUNTO
	,REINC