----------CLIENTES ISC VS PLANTA-------
DROP TABLE XXX
SELECT 
	A.*
	,B.CA_DOC
	,B.CN_ID_ASSINATURA
	,B.CN_ASSINANTE
	,B.CN_STS_ASS
	,B.DT_INST_ASS
INTO XXX
FROM XXX A ----ALTERAR QUANDO QUISER PEGAR OUTROS MESES
LEFT JOIN XXX (nolock) B
ON (A.TERMINAL IN (CONVERT(VARCHAR,B.NM_DDD_CEL)+CONVERT(VARCHAR,B.NM_TEL_CEL),
CONVERT(VARCHAR,B.NM_DDD_COM)+CONVERT(VARCHAR,B.NM_TEL_COM),
CONVERT(VARCHAR,B.NM_DDD_RES)+CONVERT(VARCHAR,B.NM_TEL_RES)))
OR(A.TELEFONO1 IN (CONVERT(VARCHAR,B.NM_DDD_CEL)+CONVERT(VARCHAR,B.NM_TEL_CEL),
CONVERT(VARCHAR,B.NM_DDD_COM)+CONVERT(VARCHAR,B.NM_TEL_COM),
CONVERT(VARCHAR,B.NM_DDD_RES)+CONVERT(VARCHAR,B.NM_TEL_RES)))
OR A.CLIENTE = B.AN_NOME


---------------RECORTE XXX------------
--DROP TABLE XXX
--select 
--		codSolicitacao = replace(codSolicitacao,'.','')
--		,cnpjUsuario = cast(replace(nullif(cnpjUsuario,''),'/','') as bigint) 
--		,cpfUsuario = cast(replace(nullif(cpfUsuario,''),'/','') as bigint) 
--		,dataRegistroSolicitacao = cast(dataRegistroSolicitacao as date)
--		,motivo
--		,foneContato1
--		,foneContato2
--		INTO XXX
--		from XXX (nolock)
--		where servico = 'TV por Assinatura'
--		and dataregistrosolicitacao >= '2013-10-01'

--		INSERT INTO XXX
--		select 
--		codSolicitacao = replace(codSolicitacao,'.','')
--		,cnpjUsuario = cast(replace(nullif(cnpjUsuario,''),'/','') as bigint) 
--		,cpfUsuario = cast(replace(nullif(cpfUsuario,''),'/','') as bigint) 
--		,dataRegistroSolicitacao = cast(dataRegistroSolicitacao as date)
--		,motivo
--		,foneContato1
--		,foneContato2
--		from XXX (nolock)
--		where servico = 'TV por Assinatura'
--		and dataregistrosolicitacao >= '2013-10-01'
		
--------RETIRA DUPLICADAS XXX

--SELECT A.*
--INTO XXX
--FROM
--(SELECT *
--,row_number() over(partition by codSolicitacao order by dataregistrosolicitacao desc) AS REP
--FROM XXX)	A WHERE REP = '1'	


----------RECORTE BDS--------
--DROP TABLE XXX
--SELECT 	
--  B.CN_ID_ASSINATURA
--  ,B.NM_SEQ_OS
--	,B.DT_ABERT	 
--	,B.AN_MOT_OS	 
--	,B.CA_TP_OS	
--	,B.CA_SERV_OS
--	,CASE WHEN B.NM_SEQ_OS = C.NM_SEQ_OS AND C.DT_BAIXA IS NOT NULL AND C.DT_BAIXA <= C.DT_PRIM_AGENDA THEN 'S'
--	WHEN B.NM_SEQ_OS = D.NM_SEQ_OS AND D.DT_BAIXA IS NOT NULL AND D.DT_BAIXA <= D.DT_PRIM_AGENDA THEN 'S' 
--	ELSE 'N' END CUMPR_PRIM_AG
--	,CASE WHEN B.NM_SEQ_OS = C.NM_SEQ_OS AND C.DT_BAIXA IS NOT NULL AND C.DT_BAIXA <= C.DT_AGENDA THEN 'S'
--	WHEN B.NM_SEQ_OS = D.NM_SEQ_OS AND D.DT_BAIXA IS NOT NULL AND D.DT_BAIXA <= D.DT_AGENDA THEN 'S' 
--	ELSE 'N' END CUMPR_AG
--	,CASE WHEN B.NM_SEQ_OS = C.NM_SEQ_OS THEN C.DT_BAIXA
--	WHEN B.NM_SEQ_OS = D.NM_SEQ_OS THEN D.DT_BAIXA 
--	ELSE NULL END DT_BAIXA
--	,CASE WHEN B.NM_SEQ_OS = C.NM_SEQ_OS THEN 'CONCLUIDA' 
--	WHEN B.NM_SEQ_OS = D.NM_SEQ_OS THEN 'CANCELADA' 
--	ELSE 'EM ABERTO' END STATUS
--	,CASE WHEN B.NM_SEQ_OS = C.NM_SEQ_OS THEN C.AN_MOT_BXA_OS
--	WHEN B.NM_SEQ_OS = D.NM_SEQ_OS THEN D.AN_MOTIVO 
--	ELSE 'EM ABERTO' END MOTIVO_DETALHE	
--INTO XXX	
--FROM (XXX WHERE DT_ABERT >='2013-09-01' AND CN_ID_ASSINATURA IS NOT NULL) B	
--LEFT JOIN (SELECT * FROM XXX WHERE DT_ABERT >='2013-09-01') C	
--ON B.NM_SEQ_OS = C.NM_SEQ_OS	
--LEFT JOIN (SELECT * FROM XXX WHERE DT_ABERT >='2013-09-01') D	
--ON B.NM_SEQ_OS = D.NM_SEQ_OS	
--WHERE B.CA_TP_OS IN ('AT') AND B.CN_TP_NEGOCIO IN ('1','2')

----------ISC COMPL----------

DROP TABLE XXX

SELECT C.*
INTO XXX
FROM
(SELECT 
	A.DATA_ID
	,CASE WHEN B.CODSOLICITACAO IS NOT NULL THEN 'S' ELSE 'N' END XXX
	,B.MOTIVO AS MOTIVO_XXX
	,ROW_NUMBER () OVER (PARTITION BY A.DATA_ID ORDER BY B.DATAREGISTROSOLICITACAO ASC) AS REINCIDENCIA_XXX
	,ROW_NUMBER () OVER (PARTITION BY A.DATA_ID ORDER BY B.DATAREGISTROSOLICITACAO DESC) AS REP
FROM XXX A
INNER JOIN XXX B
ON ((A.CA_DOC IS NOT NULL AND A.CA_DOC IN (B.CPFUSUARIO,B.CNPJUSUARIO))
OR (A.TERMINAL IS NOT NULL AND A.TERMINAL <> '' AND A.TERMINAL IN (B.FONECONTATO1,B.FONECONTATO2))
OR (A.TELEFONO1 IS NOT NULL AND A.TELEFONO1 <> '' AND A.TELEFONO1 IN (B.FONECONTATO1,B.FONECONTATO2)))
AND A.DATA >= B.DATAREGISTROSOLICITACAO
AND DATEDIFF (MONTH,B.DATAREGISTROSOLICITACAO,A.DATA) <=6) C WHERE REP ='1'

----------ISC BD----------

DROP TABLE XXX

SELECT C.*
INTO XXX
FROM
(SELECT 
	A.DATA_ID
	,CASE WHEN B.NM_SEQ_OS IS NOT NULL THEN 'S' ELSE 'N' END BD
	,B.MOTIVO_DETALHE AS MOTIVO_BD
	,B.CUMPR_PRIM_AG
	,B.STATUS AS STATUS_BD
	,ROW_NUMBER () OVER (PARTITION BY A.DATA_ID ORDER BY B.DT_ABERT ASC) AS REINCIDENCIA_BD
	,ROW_NUMBER () OVER (PARTITION BY A.DATA_ID ORDER BY B.DT_ABERT DESC) AS REP
FROM XXX A
INNER JOIN XXX B
ON A.CN_ID_ASSINATURA IS NOT NULL 
AND A.CN_ID_ASSINATURA = B.CN_ID_ASSINATURA
AND A.DATA >= B.DT_ABERT
AND DATEDIFF (MONTH,B.DT_ABERT,A.DATA) <=6 ) C WHERE REP ='1'

----------ISC CALL----------

DROP TABLE XXX

SELECT C.*
INTO XXX
FROM
(SELECT 
	A.DATA_ID
	,CASE WHEN B.CA_PROTOC_ATE IS NOT NULL THEN 'S' ELSE 'N' END CHAMADA
	,B.MOTIVO AS MOTIVO_CHAMADA
	,ROW_NUMBER () OVER (PARTITION BY A.DATA_ID ORDER BY B.DT_ATEND ASC) AS REINCIDENCIA_CHAMADA
	,ROW_NUMBER () OVER (PARTITION BY A.DATA_ID ORDER BY B.DT_ATEND DESC) AS REP
FROM XXX A
INNER JOIN XXX B
ON A.CN_ID_ASSINATURA IS NOT NULL 
AND A.CN_ID_ASSINATURA = B.CN_ID_ASSINATURA
AND A.DATA >= B.DT_ATEND
AND DATEDIFF (MONTH,B.DT_ATEND,A.DATA) <=6 ) C WHERE REP ='1'

----------ISC OSI AJUT----------

DROP TABLE XXX

SELECT C.*
INTO XXX
FROM
(SELECT 
	A.DATA_ID
	,CASE WHEN B.CN_SEQ_FILA_OSI IS NOT NULL THEN 'S' ELSE 'N' END OSI
	,CASE WHEN DATEDIFF (DAY,B.DT_CRIACAO,B.DT_ENCERRAMENTO) <= '5' THEN 'S' 
	ELSE 'N' END PRAZO_OSI
	,ROW_NUMBER () OVER (PARTITION BY A.DATA_ID ORDER BY B.DT_CRIACAO ASC) AS REINCIDENCIA_OSI
	,ROW_NUMBER () OVER (PARTITION BY A.DATA_ID ORDER BY B.DT_CRIACAO DESC) AS REP
FROM XXX A
INNER JOIN XXX B
ON A.CN_ID_ASSINATURA IS NOT NULL 
AND A.CN_ID_ASSINATURA = B.CN_ID_ASSINATURA
AND A.DATA >= B.DT_CRIACAO
AND DATEDIFF (MONTH,B.DT_CRIACAO,A.DATA) <=6 ) C WHERE REP ='1'


----------ISC CCON----------

DROP TABLE XXX

SELECT C.*
INTO XXX
FROM
(SELECT 
	A.DATA_ID
	,CASE WHEN B.CN_SEQ_NEG IS NOT NULL THEN 'S' ELSE 'N' END CCON
	,CASE WHEN B.CA_TIPO_TAB = 'S' THEN 'RETIDO' WHEN B.CA_TIPO_TAB = 'N' THEN 'NÃO RETIDO' ELSE 'IMPRODUTIVA' END STATUS_RETENÇÃO
	,CASE WHEN B.CN_SEQ_SUB_DESAB NOT IN ('') AND DATEDIFF (DAY,B.DT_ENTRADA,B.DT_ENCERRA) <='1' THEN 'CRITICA' 
	WHEN B.CN_SEQ_SUB_DESAB ='' THEN 'ABERTA' ELSE 'ENCERRADA' END STATUS_CCON
	,ROW_NUMBER () OVER (PARTITION BY A.DATA_ID ORDER BY B.DT_ENTRADA ASC) AS REINCIDENCIA_CCON
	,ROW_NUMBER () OVER (PARTITION BY A.DATA_ID ORDER BY B.DT_ENTRADA DESC) AS REP
FROM XXX A
INNER JOIN (SELECT * FROM XXX WHERE CA_CAMPANHA IN ('CCON_MULTA','CCON')) B
ON A.CN_ID_ASSINATURA IS NOT NULL 
AND A.CN_ID_ASSINATURA = B.CN_ID_ASSINATURA
AND A.DATA >= B.DT_ENTRADA
AND DATEDIFF (MONTH,B.DT_ENTRADA,A.DATA) <=6 ) C WHERE REP ='1'

---------------CONSOLIDAÇÃO DAS BASES------------------
SELECT 
	A.*
	,B.XXX
	,B.MOTIVO_XXX
	,B.REINCIDENCIA_XXX
	,C.BD
	,C.MOTIVO_BD
	,C.CUMPR_PRIM_AG
	,C.STATUS_BD
	,C.REINCIDENCIA_BD
	,D.CHAMADA
	,D.MOTIVO_CHAMADA
	,D.REINCIDENCIA_CHAMADA
	,E.OSI
	,E.PRAZO_OSI
	,E.REINCIDENCIA_OSI
	,F.CCON
	,F.STATUS_RETENÇÃO
	,F.STATUS_CCON
	,F.REINCIDENCIA_CCON
FROM XXX A
LEFT JOIN XXX B
ON A.DATA_ID = B.DATA_ID
LEFT JOIN XXX C
ON A.DATA_ID = C.DATA_ID
LEFT JOIN XXX D
ON A.DATA_ID = D.DATA_ID
LEFT JOIN XXX E
ON A.DATA_ID = E.DATA_ID
LEFT JOIN XXX F
ON A.DATA_ID = F.DATA_ID
	
	