SELECT 
	*
FROM
(SELECT  
  A.CN_ID_ASSINATURA
  ,A.CN_SEQ_NEG
  ,A.CA_CAMPANHA
  ,A.CA_STS_NEG
  ,A.DT_ENTRADA
  ,A.CA_USR_INCLU
  ,A.CN_STS_ASS
  ,A.CA_OPERADOR
  ,A.CA_TABULACAO
  ,A.DT_ENCERRA
  ,A.CN_SEQ_HIST_DESAB 
  ,A.CN_SEQ_SUB_DESAB
  ,B.CA_AREA
  ,B.CA_TP_OPR
  ,CASE WHEN A.CN_STS_ASS = '4' THEN 'PDSX'
  WHEN A.CN_STS_ASS = '6' THEN 'DESC' ELSE 'PENDENTE' END STATUS_CANC
  ,CASE WHEN CN_SEQ_HIST_DESAB IS NULL AND CN_SEQ_SUB_DESAB IS NULL AND (SYSDATE-A.DT_ENTRADA ) >1 THEN 'CRITICA' ELSE 'NORMAL' END PDSX_S_OU_N
	,ROW_NUMBER () OVER(PARTITION BY A.CN_ASSINANTE ORDER BY A.DT_ENTRADA ASC) REINC
	,ROW_NUMBER () OVER(PARTITION BY A.CN_ASSINANTE ORDER BY A.DT_ENTRADA DESC) REP
FROM INT_GCA_NEGOCIACAO A
LEFT JOIN INT_ADM_OPERADOR B
ON A.CA_USR_INCLU = B.CA_USR
where ca_grp_negocio = 'DTH'
and dt_entrada >='15/11/13'
and dt_entrada <'15/01/14'
AND CN_ID_ASSINATURA IN (xxx)) C WHERE REP = 1
