/******ABSOLUTE NUMBER***********/
SELECT ABS(66), ABS(-66)

/********CEILING() - RETURNS THE SMALLEST INTEGER VALUE NOT LESS THAN THE ARGUMENT - ROUND THE NUMBER PRA BAIXO******/
SELECT CEILING(12.34), CEILING (-12.34)

/********FLOOR() - RETURNS THE LARGEST INTEGER VALUE NOT GREATER THAN THE ARGUMENT - ROUND THE NUMBER PRA CIMA******/
SELECT FLOOR(12.34), FLOOR (-12.34)

/********PI () - PI VALUE******/
SELECT PI()

/********DEGREES () - CONVERT RADIANS TO DEGREES******/
SELECT DEGREES(PI()), DEGREES(PI()/2)

/********POWER () ******/
SELECT POWER(8,2)

/********SQRT () ******/
SELECT SQRT(4)
SELECT SQRT(64)
--SELECT SQRT(-256)